# Development Url
#baseUrl: http://localhost:4000

# Production Url
baseUrl: https://gamedevbr-podcast.github.io

# Social Media
linkGithub: https://github.com/gamedevbr-podcast

# Site Settings
title: GameDevBr Podcast
description: GameDevBr Podcast
email: gamedevbr.podcast@gmail.com
paginate: 20
permalink: /:title/
post_dirs: false

# Build Settings
gems:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
feed:
  path: rss.xml

# Podcast Settings
licence: CC-BY-CA
author: GameDevBr
email: gamedevbr.podcast@gmail.com
podcast:
  title: GameDevBr
  art: http://link/to/cover/art.png
  category: Education
  subcategories:
  - Training
  subtitle: The subtitle that shows in "Description" column on desktop iTunes
  summary: >
    A long long description of your podcast
    that a listener can read in Podcast View.
