# Development Url
#baseUrl: http://localhost:4000

# Production Url
baseUrl: https://gamedevbr-podcast.github.io

# Social Media
linkGithub: https://github.com/gamedevbr-podcast

# Site Settings
title: GameDevBr Podcast
description: GameDevBr Podcast
email: gamedevbr.podcast@gmail.com
paginate: 20
permalink: /:title/
post_dirs: false

# Build Settings
gems:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
feed:
  path: rss.xml
